<?php
/**
 * @copyright Copyright (C) 2008 City of Bloomington, Indiana. All rights reserved.
 * @license http://www.gnu.org/licenses/agpl.txt GNU/AGPL, see LICENSE.txt
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 */
	echo $this->includeBlocks();
?>
You have received this message from the City of Bloomington through
our website's automated email notification system.  Please ignore this
message if you have received it in error.  Email messages sent to this
address will not be answered.