<?php
/**
 * @copyright Copyright (C) 2007 City of Bloomington, Indiana. All rights reserved.
 * @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.txt
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 */
?>
<div class="widget">
	<h1>City Officials</h1>
	<ul><li><a href="/mayor"><h2>Mayor Mark Kruzan</h2></a></li>
		<li><a href="/mayor/"><img src="/media/media.php?media_id=1467" alt="Mayor Mark Kruzan" /> Mayor Home</a></li>
		<li><a href="/mayor">Biography</a></li>
		<li><a href="/newsflash">Newsflash</a></li>
	</ul>

	<ul><li><a href="/city-council"><h2>City Council</h2></a></li>
		<li><a href="/city-council"><img src="/media/media.php?media_id=1466" alt="Bloomington Common Council" /> City Council Home</a></li>
		<li><a href="/documents/viewDocument.php?document_id=472">Legislation Center</a></li>
	</ul>

	<ul><li><a href="/city-clerk"><h2>City Clerk</h2></a></li>
		<li><a href="/city-clerk"><img src="/media/media.php?media_id=1465" alt="City Clerk Regina Moore" /> City Clerk Home<a></li>
		<li><a href="/boards-and-commissions">Boards and Commissions</a></li>
	</ul>
</div>
