<?php
/**
 * @copyright Copyright (C) 2007 City of Bloomington, Indiana. All rights reserved.
 * @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.txt
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 */
?>
<p>Could not create the backup.  Check the permissions on the backup directory.
Make sure that Apache has permission to write to <?php echo APPLICATION_HOME; ?>/data/backups</p>