<?php
/**
 * @copyright Copyright (C) 2007 City of Bloomington, Indiana. All rights reserved.
 * @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.txt
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 */
?>
<p>That file has already been uploaded.</p>
<p>Someone has previously uploaded that file; it is already on the server.  To find it,
you should <strong>Browse for an existing attachment</strong>, and attach that file to this document.</p>