<?php
/**
 * @copyright Copyright (C) 2007 City of Bloomington, Indiana. All rights reserved.
 * @license http://www.gnu.org/licenses/agpl.txt GNU/AGPL, see LICENSE.txt
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 */
?>
<p>Your file was <strong>not</strong> uploaded successfully.  Most likely you
tried to upload a file that was too big.  The current size limit for uploaded files
is <?php echo ini_get('upload_max_filesize'); ?></p>
