<div id="mainContent">
<h2>Attachments [file:____.__]</h2>
<table>
<tr><td colspan="2">Creates a link to a file that has been uploaded to the site.
			The file can be of any type: image, PDF, Word Doc, etc.
			The link will allow the user to <strong>download </strong>the file.</td>
</tr><tr><td>
e.g.

	</td>
	<td>[file:grant_application.pdf] [file:bloomington_map.gif] [file:safety_tips.doc] </td></tr><tr>
		<td colspan="2">Note: in the case of images, this will not display the image.
			If you want the image displayed, see the syntax for either
			[image:] or [thumbnail:]</p>	</td>
</tr>
</table>
</div>