<div id="mainContent">
<h2>Facets</h2>
<p>Link to a facet group by using the facet's id number or name.</p>
<table><tbody><tr><th><p>Service Guides:</p></th><th>Topics</th></tr><tr><td>
<ul><li>Business - 28</li><li>For Kids - 6<br>
</li>
<li>Local Arts - 1</li>
<li>Nonprofits -31</li>
<li>Residents - 3</li>
<li>Students - 4</li>
<li>Visitors - 7</li>
<li>Volunteers - 5 </li>
<li>Voters - 8</li></ul></td><td>
<ul><li>Arts, Culture & Recreation - 23</li><li>Business & Commerce - 2</li>
<li>City Government - 15</li>
<li>Civic Engagement &amp; Democracy - 33 </li>
<li>Education &amp; Learning  - 16 </li>
<li>Family Living  - 20</li>
<li>Diversity &amp; Inclusion - 38</li>
<li>Environment &amp; Green Living - 14</li>
<li>Finance, Licenses &amp; Benefits - 37</li>
<li>Health and Social Wellness - 9</li>
<li>Housing &amp; Neighborhoods - 32</li>
<li>Jobs and Careers - 22</li>
<li>Pets &amp; Animal Welfare - 21 </li>
<li>Public Safety - 17 </li>
<li>Public Works &amp; Utilities - 16 </li>
<li>Rights &amp; Legal Services -35</li>
<li>Technology - 30</li>
<li>Transportation &amp; Parking- 34         </li>
</ul></td></tr></tbody></table>
<table><tbody><tr><th colspan="2">[facet:___]</th></tr><tr><th colspan="2">By Name</th></tr><tr><td>A Service Guide</td><td><br>[facet:Resident's Guide]</td></tr><tr><td>A Topic</td><td>[facet:Public Safety]</td></tr><tr><th colspan="2">By Number</th></tr><tr>
  <td>Arts, Culture &amp; Recreation </td>
  <td>[facet:23]</td></tr></tbody></table>
</div>
