<div id="mainContent">
<h2>Images</h2>
<table><tr><th colspan="2">[image: _______]</th></tr><tr><td colspan="2">e.g.</td>
 </tr><tr><td>number displayed in image gallery</td><td>[image:205]</td></tr><tr><td>
 filename</td><td>[image:cityhall.jpg]</td></tr>
<tr><th colspan="2">Images with Captions</th></tr><tr><td colspan="2">[Insert Caption Here|image:_______]</td></tr><tr><td>
e.g.</td><td>[City Hall at Dusk|image:cityhall.jpg]</td></tr><tr><th colspan="2">Images with Right or Left Alignment</th></tr><tr><td colspan="2">Will align image to left or right with text wrapping around it.
</td></tr><tr colspan="2"><td>
e.g.</td>
<td>[image:cityhall.jpg,left]</td>
</tr><tr><td></td><td>[image:_____,right]</td></tr></table>
</div>
