<div id="mainContent">
<h2>Links</h2>
<h3>Internal Links</h3>


<h4>Anchors [anchor:_____]</h4>
<table>
<tr><th>If the anchor you are linking to is on the same page</th>
	<td>[#anchorname]</td></tr>
<tr><th>If the anchor is on a different page</th>
	<td>[Page Title#anchorname]</td></tr>
</table>

<h4>To Another Document [Page Title]</h4>
<table>
<tr><th>e.g.</th>
	<td><div>[Information and Technology Services]</div>
		<div>[Map Gallery]</div>
	</td>
</tr>
</table>

<h4>To an Email Address [mailto:_____]</h4>
<table>
<tr><th>e.g.</th>
	<td>[mailto:browne@bloomington.in.gov]</td></tr>
</table>

<h4>To a Calendar [calendar:____]</h4>
<table>
<tr><th>e.g.</th>
	<td></td></tr>
<tr><th>Show All Calendars</th>
	<td>[calendar:all]</td></tr>
<tr><th>Government Calendar</th>
	<td>[calendar:goverment]</td></tr>
</table>

<h4>To an Event [event:___]</h4>
<table>
<tr><th>e.g.</th>
	<td></td></tr>
<tr><th>Use the Title of the Event</th>
	<td>[event:Environmental Commission Meeting]</td></tr>
<tr><th>To point to a specific occurence of an Event, just provide the date</th>
	<td>[event:/2008/2/22/MPO Technical Advisory Committee]</td></tr>
</table>

<h4>To a Location Group [location group:____]</h4>
<table>
<tr><th>e.g.</th>
	<td>[location group:public art]</td></tr>
</table>

<h4>To a Location [location:____]</h4>
<table>
<tr><th>e.g.</th>
	<td></td></tr>
<tr><th>Without a caption</th>
	<td>[location:Bryan Park]</td></tr>
</table>

<h3>External Links</h3>
<h4>External Links take you to a page outside of the City's Website</h4>
<table>
<tr><th>e.g.</th>
	<td>[http:www.iub.edu/]</td></tr>
</table>
</div>
