<div id="mainContent">
<h2>Links</h2>
<h3>Internal Links</h3>
<table>
<tr><th colspan="2">Anchors [anchor:_____]</th></tr><tr><td>If the anchor you are linking to is on the same page</td>
<td>[link text|#anchorname]</td>
</tr><tr><td>If the anchor is on a different page</td>
<td>[link text|Page Title#anchorname]</td>
</tr>
<tr>
  <th colspan="2">To Another Document [Page Title]</th>
</tr><tr><td>e.g.</td><td>[Information and Technology Services]<br>[Map Gallery]</td>
</tr><tr><th colspan="2">To an Email Address [mailto:_____]</th></tr><tr><td>e.g.</td><td>[mailto:browne@bloomington.in.gov]</td></tr><tr><th colspan="2">To a Calendar [calendar:____]</th></tr><tr><td>e.g.<br>Show All Calendars<br>Government Calendar</td><td><br>[calendar:all]<br>[View the Government Calendar|calendar:goverment]</td></tr><tr><th colspan="2">To an Event [event:___]</th></tr><tr><td>e.g.<br>Use the Title of the Event</td><td><br>[Learn about the Environmental Commission Meeting|event:Environmental Commission Meeting]</td></tr><tr><th colspan="2">To a Location Group [location group:____]</th></tr><tr><td>e.g.<br>Without a caption<br>With a caption</td><td><br>[location group:public art]<br>[[Find Bloomington's Public Art Venues|location group:public art]</td><tr><th colspan="2">To a Location [location:____]</th></tr><tr><td>e.g. <br>Without a caption<br>With a Caption</td><td><br>[location:Bryan Park]<br>Find Bryan Park|location:Bryan Park]</td></tr></table>
<h3>External Links</h3>
<table>
<tr><td colspan="2">External Links take you to a page outside of the City's Website</td></tr>
<tr><td>e.g.</td><td>[http:www.iub.edu/]</td></tr></table>
</div>
