<div class="left sidebar">
	<div class="widget">
		<h1>Notation Guide</h1>
		<ul><li><a href="<?php echo BASE_URL; ?>/documents/notationGuide.php?page=images">Images</a>
				<ul><li><a href="<?php echo BASE_URL; ?>/documents/notationGuide.php?page=images">Images</a></li>
					<li><a href="<?php echo BASE_URL; ?>/documents/notationGuide.php?page=images">Thumbnails</a></li>
				</ul>
			</li>
			<li><a href="<?php echo BASE_URL; ?>/documents/notationGuide.php?page=attachments">Attachments</a></li>
			<li><a href="<?php echo BASE_URL; ?>/documents/notationGuide.php?page=links">Internal Links</a>
				<ul><li><a href="<?php echo BASE_URL; ?>/documents/notationGuide.php?page=links">Anchors</a></li>
					<li><a href="<?php echo BASE_URL; ?>/documents/notationGuide.php?page=links">To another document</a></li>
					<li><a href="<?php echo BASE_URL; ?>/documents/notationGuide.php?page=links">To  an email address</a></li>
					<li><a href="<?php echo BASE_URL; ?>/documents/notationGuide.php?page=links">To a calendar</a></li>
					<li><a href="<?php echo BASE_URL; ?>/documents/notationGuide.php?page=links">To an event</a></li>
					<li><a href="<?php echo BASE_URL; ?>/documents/notationGuide.php?page=links">To a location</a></li>
					<li><a href="<?php echo BASE_URL; ?>/documents/notationGuide.php?page=links">To a location group</a></li>
				</ul>
			<li><a href="<?php echo BASE_URL; ?>/documents/notationGuide.php?page=facets">Links to Facet Groups</a></li>
			<li><a href="<?php echo BASE_URL; ?>/documents/notationGuide.php?page=links">External Links</a></li>
		</ul>
	</div>
</div>