<?php
// Call LanguageTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'LanguageTest::main');
}

require_once 'PHPUnit/Framework.php';

require_once APPLICATION_HOME.'/classes/Language.inc';

/**
 * Test class for Language.
 * Generated by PHPUnit on 2007-10-04 at 11:49:08.
 */
class LanguageTest extends PHPUnit_Framework_TestCase {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('LanguageTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
    	$PDO = Database::getConnection();
    	$query = $PDO->prepare('insert languages values(?,?,?)');
    	$query->execute(array('te','Test','Test Native'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    	$PDO = Database::getConnection();
    	$query = $PDO->prepare('delete from languages where code=?');
    	$query->execute(array('te'));
    }

    /**
     * Test creating empty object
     */
    public function testCreateNewLanguage() {
    	$lang = new Language();
    	$this->assertTrue($lang instanceof Language, "expected Language object");
    }

    /**
     * Test loading an existing language from the database
     */
    public function testLoadExistingLanguage() {
		$PDO = Database::getConnection();
		$this->assertTrue($PDO instanceof PDO,"Database Object Not Present");

    	$lang = new Language('te');
    	$this->assertTrue($lang->getEnglish()=='Test',"Couldn't load the Test Language object");
    }

    /**
     * Test modifying an existing row in the database
     */
    public function testUpdate() {
    	$test = new Language('te');
    	$test->setEnglish('changed');
    	$test->save();

    	$PDO = Database::getConnection();
    	$query = $PDO->prepare('select english from languages where code=?');
    	$query->execute(array('te'));
    	$result = $query->fetchAll();
    	$this->assertEquals($result[0]['english'],'changed','Language did not get updated in the database');
    }

    /**
     * Test creating a new row in the database
     */
    public function testInsert() {
    	$new = new Language();
    	$new->setCode('ne');
    	$new->setEnglish('New');
    	$new->setNative('Native');
    	$new->save();

    	$PDO = Database::getConnection();
    	$query = $PDO->query("select * from languages where code='ne'");
    	$result = $query->fetchAll();
    	$this->assertEquals($result[0]['code'],'ne','New Language did not get created');
    	$this->assertEquals($result[0]['english'],'New','New Language did not get created');
    	$this->assertEquals($result[0]['native'],'Native','New Language did not get created');
    }

    /**
     * @todo Implement testGetCode().
     */
    public function testGetCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetEnglish().
     */
    public function testGetEnglish() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetNative().
     */
    public function testGetNative() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetEnglish().
     */
    public function testSetEnglish() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetNative().
     */
    public function testSetNative() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}

// Call LanguageTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'LanguageTest::main') {
    LanguageTest::main();
}
?>
