<?php
// Call SectionDocumentListTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'SectionDocumentListTest::main');
}

require_once 'PHPUnit/Framework.php';

require_once APPLICATION_HOME.'/classes/SectionDocumentList.inc';

/**
 * Test class for SectionDocumentList.
 * Generated by PHPUnit on 2007-10-09 at 13:24:33.
 */
class SectionDocumentListTest extends PHPUnit_Framework_TestCase {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('SectionDocumentListTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testFind().
     */
    public function testFind() {
		# Try and find a single entry.  Should only return one result
		$sectionDocumentList = new SectionDocumentList(array('section_id'=>1,'document_id'=>1));
		$count = count($sectionDocumentList);
		$this->assertTrue($count==1,"Find returned $count matches");
    }
}

// Call SectionDocumentListTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'SectionDocumentListTest::main') {
    SectionDocumentListTest::main();
}
?>
