<?php
/**
 * @copyright Copyright (C) 2007 City of Bloomington, Indiana. All rights reserved.
 * @license http://www.gnu.org/licenses/agpl.txt GNU/AGPL, see LICENSE.txt
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 *
 * This fires off the JavaScript that turns an expandable UL into a tree
 * This library has a bug - it will freeze if the <li> elements are not on their
 * own line.  Make sure to put line breaks for each <li>
 */
?>
<script type="text/javascript" src="<?php echo BASE_URL; ?>/js/tree.js"></script>
