<?php
/**
 * @copyright Copyright (C) 2006,2007 City of Bloomington, Indiana. All rights reserved.
 * @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.txt
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 */
?>
	<ul>
		<li><a href="<?php echo BASE_URL; ?>/users">Users</a></li>
		<li><a href="<?php echo BASE_URL; ?>/widgets">Widgets</a></li>
		<li><a href="<?php echo BASE_URL; ?>/departments">Departments</a></li>
	</ul>
