<?php
/**
 * @copyright Copyright (C) 2006 City of Bloomington, Indiana. All rights reserved.
 * @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.txt
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 */
?>
<div class="administrator">
	<div class="titleBar">Webmaster</div>
	<ul>
		<li><a href="<?php echo BASE_URL; ?>/documents/myDocuments.php">Documents</a></li>
		<li><a href="<?php echo BASE_URL; ?>/sections">Sections</a></li>
		<li><a href="<?php echo BASE_URL; ?>/facets">Facets</a></li>
		<li><a href="<?php echo BASE_URL; ?>/documentTypes">Document Types</a></li>
		<li><a href="<?php echo BASE_URL; ?>/locations">Locations</a></li>
		<li><a href="<?php echo BASE_URL; ?>/calendars">Calendars</a></li>
		<li><a href="<?php echo BASE_URL; ?>/media/attachments.php">Attachments</a></li>
	</ul>
</div>