<?php
/**
 * @copyright Copyright (C) 2006,2007 City of Bloomington, Indiana. All rights reserved.
 * @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.txt
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 */
?>
	<ul>
		<li><a href="<?php echo BASE_URL; ?>/documents">Documents</a></li>
		<li><a href="<?php echo BASE_URL; ?>/sections">Sections</a></li>
		<li><a href="<?php echo BASE_URL; ?>/facets">Facets</a></li>
		<li><a href="<?php echo BASE_URL; ?>/documentTypes">Document Types</a></li>
		<li><a href="<?php echo BASE_URL; ?>/locations">Locations</a></li>
		<li><a href="<?php echo BASE_URL; ?>/calendars">Calendars</a></li>
		<li><a href="<?php echo BASE_URL; ?>/media/attachments.php">Attachments</a></li>
		<li><a href="<?php echo BASE_URL; ?>/widgets">Widgets</a></li>
	</ul>
