<?php
/**
 * @copyright Copyright (C) 2007 City of Bloomington, Indiana. All rights reserved.
 * @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.txt
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 */
?>
<p>That document is no longer open for editing.  Any changes to it have <strong>not</strong>
been saved.</p>

<p>Currently, this system only supports editing one document at a time.</p>