<?php
/**
 * @copyright Copyright (C) 2007 City of Bloomington, Indiana. All rights reserved.
 * @license http://www.gnu.org/licenses/agpl.txt GNU/AGPL, see LICENSE.txt
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 */
?>
<p>That document is no longer open for editing.</p>
<p>You most likely hit your back button after saving a document.  To prevent
documents from being double-saved, we remove the saved document from your session.</p>
<p>We don't know what document you were editing, but we think this is where you came from.</p>
