#!/bin/bash
# @copyright Copyright (C) 2008 City of Bloomington, Indiana. All rights reserved.
# @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.txt
# @author Cliff Ingham <inghamn@bloomington.in.gov>
#
# Creates a tarball containing a full snapshot of the data in the site
APPLICATION_HOME=/var/www/sites/content_manager
MYSQLDUMP=/usr/local/mysql/bin/mysqldump

MYSQL_DBNAME=content_manager
MYSQL_USER=username
MYSQL_PASS=password

#----------------------------------------------------------
# No Editing Required below this line
#----------------------------------------------------------
now=`date +%s`
today=`date +%F`
num_days_to_keep=5

# Dump the database
$MYSQLDUMP -u $MYSQL_USER -p$MYSQL_PASS $MYSQL_DBNAME > $APPLICATION_HOME/data/database.sql

# Tarball the Data
tar cz -C $APPLICATION_HOME -f $APPLICATION_HOME/backups/$today.tar.gz $APPLICATION_HOME/data

# Purge any backup tarballs that are too old
for file in `ls $APPLICATION_HOME/backups`
do
	atime=`stat -c %Y $APPLICATION_HOME/backups/$file`
	if [ $(( $now - $atime >= $num_days_to_keep*24*60*60 )) = 1 ]
	then
		rm $APPLICATION_HOME/backups/$file
	fi
done
