#!/bin/bash
# @copyright Copyright (C) 2008 City of Bloomington, Indiana. All rights reserved.
# @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.txt
# @author Cliff Ingham <inghamn@bloomington.in.gov>
#
# Creates a tarball containing a full snapshot of the data in the site
APPLICATION_HOME=/var/www/sites/content_manager
MYSQLDUMP=/usr/local/mysql/bin/mysqldump

MYSQL_DBNAME=content_manager
MYSQL_USER=username
MYSQL_PASS=password

# How many days worth of tarballs to keep around
num_days_to_keep=5

#----------------------------------------------------------
# No Editing Required below this line
#----------------------------------------------------------
now=`date +%s`
today=`date +%F`

cd $APPLICATION_HOME

# Dump the database
$MYSQLDUMP -u $MYSQL_USER -p$MYSQL_PASS \
--ignore-table=$MYSQL_DBNAME.document_accesslog \
--ignore-table=$MYSQL_DBNAME.document_hits_daily \
--ignore-table=$MYSQL_DBNAME.document_hits_monthly \
--ignore-table=$MYSQL_DBNAME.document_hits_yearly \
$MYSQL_DBNAME > data/database.sql

# Tarball the Data
tar czf backups/$today.tar.gz data

# Purge any backup tarballs that are too old
for file in `ls backups`
do
	atime=`stat -c %Y backups/$file`
	if [ $(( $now - $atime >= $num_days_to_keep*24*60*60 )) = 1 ]
	then
		rm backups/$file
	fi
done
