<?php
/**
 * @copyright Copyright (C) 2007 City of Bloomington, Indiana. All rights reserved.
 * @license http://www.gnu.org/licenses/agpl.txt GNU/AGPL, see LICENSE.txt
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 */
?>
<div id="pageTitle">
	<div class="breadcrumbs">
		<ul><li><a href="<?php echo BASE_URL; ?>">Home</a></li>
			<li><a href="<?php echo BASE_URL; ?>/sitemap">Sitemap</a></li>
		</ul>
	</div>
	<h1>Sitemap</h1>
</div>
